### ISSUE TITLE
TG.INI stops to read ini file if 2 identical value names are found, but sends no warning / exception

### ISSUE THREAD

**Issue by SpouPoudret** [troygeiger/TG.INI#3]
I have a long ini file, and the INI library did not seems to read it entirely after I added new values.  I finally found out that there was 2 identical lines, and when TG.INI reads the second, identical, line, it simply crashed without any message nor exception. I would have expected  something in the line of "duplicate value name found".

I now have a note that will remind me of the situation.  But I tough that you might be interested to know about that.

To test, use this ini:
```
GlobalEntry="Yes"
[Test]
Pass=True
Pass=False
NumberValue=1
ColorValue="Red"
PointValue="{X=1.1,Y=2.2}"
```

Pass will have it's value set to True, then *not* set to false, and NumberValue, ColorValue and PointValue will never be read.

**Comment by troygeiger** [comment]
Nice catch! There is a try/catch while reading. I will remove that and return an exception stating the name and section of the duplicate.
I also found that there isn't a duplicate check for sections that I will be implementing.
